// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtbnbJWfQpG3NBoX9UTEIEXocZ01UVhpw',
    appId: '1:397950061968:web:937aa3f6610e422ae1b715',
    messagingSenderId: '397950061968',
    projectId: 'learn-flow-6d419',
    authDomain: 'learn-flow-6d419.firebaseapp.com',
    storageBucket: 'learn-flow-6d419.firebasestorage.app',
    measurementId: 'G-S7Y8MRQCDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk-AVYb7ad4UykelM85SxNIf7zwnGmLog',
    appId: '1:397950061968:android:2ea6abb4af54030ce1b715',
    messagingSenderId: '397950061968',
    projectId: 'learn-flow-6d419',
    storageBucket: 'learn-flow-6d419.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBri-h8Ff5YEjlPZ5OVneDbh_pVvt7owZE',
    appId: '1:397950061968:ios:b0f685f4ddff7f25e1b715',
    messagingSenderId: '397950061968',
    projectId: 'learn-flow-6d419',
    storageBucket: 'learn-flow-6d419.firebasestorage.app',
    iosBundleId: 'com.example.learnFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBri-h8Ff5YEjlPZ5OVneDbh_pVvt7owZE',
    appId: '1:397950061968:ios:b0f685f4ddff7f25e1b715',
    messagingSenderId: '397950061968',
    projectId: 'learn-flow-6d419',
    storageBucket: 'learn-flow-6d419.firebasestorage.app',
    iosBundleId: 'com.example.learnFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtbnbJWfQpG3NBoX9UTEIEXocZ01UVhpw',
    appId: '1:397950061968:web:76b0b93037c31a8de1b715',
    messagingSenderId: '397950061968',
    projectId: 'learn-flow-6d419',
    authDomain: 'learn-flow-6d419.firebaseapp.com',
    storageBucket: 'learn-flow-6d419.firebasestorage.app',
    measurementId: 'G-BJ87DPW650',
  );
}
